name: Checks
on: push
jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          clangFormatVersion: 16
